services:
  db:
    image: mysql:8.4
    container_name: instrument-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: instrument_reference_db
      MYSQL_USER: instrument_user
      MYSQL_PASSWORD: instrument_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: InstrumentReferenceDataService/Dockerfile
    container_name: instrument-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5105
      EnableHttpsRedirection: "false"
      ConnectionStrings__DefaultConnection: Server=db;Port=3306;Database=instrument_reference_db;User=instrument_user;Password=instrument_password;
    ports:
      - "5105:5105"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: instrument-frontend
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  mysql_data:
