// <auto-generated />
using System;
using InstrumentReferenceDataService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstrumentReferenceDataService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811131711_AddReferenceDataModel")]
    partial class AddReferenceDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InstrumentReferenceDataService.Models.AssetClass", b =>
                {
                    b.Property<string>("AssetClassId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AssetClassId");

                    b.ToTable("AssetClasses");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CurrencyId"));

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Exchange", b =>
                {
                    b.Property<int>("ExchangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExchangeId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MicCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ExchangeId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.IdentifierType", b =>
                {
                    b.Property<string>("IdentifierTypeId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("IdentifierTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdentifierTypeId");

                    b.ToTable("IdentifierTypes");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Instrument", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("AssetClassId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<int>("IssuerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastUpdated")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PrimaryIsin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("InstrumentId");

                    b.HasIndex("AssetClassId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("IssuerId");

                    b.HasIndex("PrimaryIsin")
                        .IsUnique();

                    b.HasIndex("SectorId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.InstrumentAudit", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ChangeSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("AuditId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("InstrumentAudits");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.InstrumentIdentifier", b =>
                {
                    b.Property<string>("IdentifierId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("IdentifierTypeId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("IdentifierValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("IdentifierId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("IdentifierTypeId", "IdentifierValue")
                        .IsUnique();

                    b.ToTable("InstrumentIdentifiers");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Issuer", b =>
                {
                    b.Property<int>("IssuerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IssuerId"));

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IssuerId");

                    b.ToTable("Issuers");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectorId"));

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SectorId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Exchange", b =>
                {
                    b.HasOne("InstrumentReferenceDataService.Models.Currency", "Currency")
                        .WithMany("Exchanges")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Instrument", b =>
                {
                    b.HasOne("InstrumentReferenceDataService.Models.AssetClass", "AssetClass")
                        .WithMany("Instruments")
                        .HasForeignKey("AssetClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstrumentReferenceDataService.Models.Currency", "Currency")
                        .WithMany("Instruments")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstrumentReferenceDataService.Models.Exchange", "Exchange")
                        .WithMany("Instruments")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstrumentReferenceDataService.Models.Issuer", "Issuer")
                        .WithMany("Instruments")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstrumentReferenceDataService.Models.Sector", "Sector")
                        .WithMany("Instruments")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetClass");

                    b.Navigation("Currency");

                    b.Navigation("Exchange");

                    b.Navigation("Issuer");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.InstrumentAudit", b =>
                {
                    b.HasOne("InstrumentReferenceDataService.Models.Instrument", "Instrument")
                        .WithMany("Audits")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.InstrumentIdentifier", b =>
                {
                    b.HasOne("InstrumentReferenceDataService.Models.IdentifierType", "IdentifierType")
                        .WithMany("InstrumentIdentifiers")
                        .HasForeignKey("IdentifierTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstrumentReferenceDataService.Models.Instrument", "Instrument")
                        .WithMany("Identifiers")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentifierType");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.AssetClass", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Currency", b =>
                {
                    b.Navigation("Exchanges");

                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Exchange", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.IdentifierType", b =>
                {
                    b.Navigation("InstrumentIdentifiers");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Instrument", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Issuer", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("InstrumentReferenceDataService.Models.Sector", b =>
                {
                    b.Navigation("Instruments");
                });
#pragma warning restore 612, 618
        }
    }
}
